### ISSUE TITLE
Architecture arm64

### ISSUE THREAD

**Issue by katgithubkat** [madamow/pymoogi#28]
Hi, when I run the makefile, the following message appears for all the .o files 
"ld: warning: ignoring file 'Wavecalc.o': found architecture 'x86_64', required architecture 'arm64'
Undefined symbols for architecture arm64:
  "_main", referenced from:
      <initial-undefines>
ld: symbol(s) not found for architecture arm64
collect2: error: ld returned 1 exit status
make: *** [MOOG] Error 1
" 
I'm trying to install pymoogi in my sonoma mac.
Thanks, Katia

**Comment by madamow** [comment]
Hi!
Your issue is not coming from pymoogi or MOOG but is specific to your machine and how it is configured. You are trying to compile the Fortran Code using libraries for x86_64 architecture (designed for Intel and AMD processors) while you apparently have a Mac with an M processor. Did you recently upgrade your Mac and migrate the system? This might be one of the causes for that. 

I can’t help you solve this, but I suggest you ensure that your compilers match your system architecture. If not, I would reinstall Xcode and other relevant libraries, ensuring they match your system.

**Comment by madamow** [comment]
This issue is not relevant to the pymoogi code.

**Comment by katgithubkat** [comment]
Thank you very much!

Katia
